version: '3.8'

services:
  app:
    container_name: tools-shop-nest-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
